"""Initial schema with all tables

Revision ID: 7b570d46009c
Revises: 
Create Date: 2026-09-09 19:19:43.165855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b570d46009c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.String(length=50), nullable=False, comment="Challenge identifier (e.g., 'hole-001')"),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Display name of the challenge'),
    sa.Column('difficulty', sa.String(length=20), nullable=True, comment="Difficulty level: 'easy', 'medium', 'hard', 'expert'"),
    sa.Column('task_type', sa.String(length=50), nullable=True, comment="Type of task: 'coding', 'extraction', 'question_answering', 'generation'"),
    sa.Column('config_yaml', sa.Text(), nullable=False, comment='Full YAML configuration for this challenge'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When challenge was loaded into database'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenges'))
    )
    op.create_index(op.f('ix_challenges_difficulty'), 'challenges', ['difficulty'], unique=False)
    op.create_index(op.f('ix_challenges_task_type'), 'challenges', ['task_type'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Session UUID'),
    sa.Column('course_id', sa.String(length=100), nullable=False, comment="Which course this session uses (e.g., 'beginner-course')"),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When session was created'),
    sa.Column('timeout_hours', sa.Integer(), nullable=False, comment='Session timeout in hours'),
    sa.Column('status', sa.String(length=20), nullable=False, comment="Session status: 'active', 'completed', 'dnf'"),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='When session expires (created_at + timeout_hours)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_course_id'), 'sessions', ['course_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique user identifier'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Auto-generated username (Color-Course-Club format)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When user account was created'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether user account is active'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique attempt identifier'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User who made this attempt'),
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='Session this attempt belongs to'),
    sa.Column('challenge_id', sa.String(length=50), nullable=False, comment='Challenge this attempt is for'),
    sa.Column('attempt_number', sa.Integer(), nullable=False, comment='Attempt number for this user on this challenge (1, 2, 3, ...)'),
    sa.Column('prompt', sa.Text(), nullable=False, comment="User's prompt submitted to LLM"),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment="User's system prompt for this attempt (may be modified from default)"),
    sa.Column('context_files', sa.JSON(), nullable=True, comment='Which context files were active for this attempt (JSON array)'),
    sa.Column('response', sa.Text(), nullable=True, comment='LLM response text'),
    sa.Column('input_tokens', sa.Integer(), nullable=False, comment='Input tokens (includes system prompt tokens)'),
    sa.Column('output_tokens', sa.Integer(), nullable=False, comment='Output tokens'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='Total tokens (input + output)'),
    sa.Column('is_correct', sa.Boolean(), nullable=False, comment='Whether this attempt passed validation'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When attempt was made'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_attempts_challenge_id_challenges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_attempts_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempts'))
    )
    op.create_index(op.f('ix_attempts_challenge_id'), 'attempts', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_attempts_session_id'), 'attempts', ['session_id'], unique=False)
    op.create_index(op.f('ix_attempts_user_id'), 'attempts', ['user_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique score record identifier'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User this score belongs to'),
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='Session this score belongs to'),
    sa.Column('challenge_id', sa.String(length=50), nullable=False, comment='Challenge this score is for'),
    sa.Column('total_attempts', sa.Integer(), nullable=False, comment='Total number of attempts made'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='Running total of all tokens used across all attempts'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='When user successfully completed this challenge (first correct attempt)'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_scores_challenge_id_challenges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_scores_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scores_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scores')),
    sa.UniqueConstraint('user_id', 'session_id', 'challenge_id', name='uq_user_session_challenge')
    )
    op.create_index(op.f('ix_scores_challenge_id'), 'scores', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_scores_session_id'), 'scores', ['session_id'], unique=False)
    op.create_index(op.f('ix_scores_user_id'), 'scores', ['user_id'], unique=False)
    op.create_table('session_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique participant record identifier'),
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='Session this participation belongs to'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User participating in session'),
    sa.Column('joined_at', sa.DateTime(), nullable=False, comment='When user joined this session'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_participants_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_session_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_participants')),
    sa.UniqueConstraint('session_id', 'user_id', name='uq_session_user')
    )
    op.create_index(op.f('ix_session_participants_session_id'), 'session_participants', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_participants_user_id'), 'session_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_participants_user_id'), table_name='session_participants')
    op.drop_index(op.f('ix_session_participants_session_id'), table_name='session_participants')
    op.drop_table('session_participants')
    op.drop_index(op.f('ix_scores_user_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_session_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_challenge_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_attempts_user_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_session_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_challenge_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sessions_course_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_challenges_task_type'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_difficulty'), table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
